// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool using the template near this directory.
//     Please see this solution for more details: Codegen\Codegen.sln
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------<%
enums.forEach(item => { %>
export { <%= item.name %> } from './<%= item.fileName %>';<%
});
models.forEach(model => { %>
export { <%= model.name %> } from '<%= utils.customExists(model) ? '../custom/' : './' %><%= model.fileName %>';<%
}); %>
