// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool using the template near this directory.
//     Please see this solution for more details: Codegen\Codegen.sln
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------<%
controllers.forEach(item => { %>
export { <%= item.name %>Service } from './<%= item.fileName %>';<%
}); %>
